### ISSUE TITLE
Printability: XZ and YZ curvature

### ISSUE THREAD

**Issue by Schreibmaschine-Berlin** [gestalte-design/zine-machine#4]
In general there are too many curves on the XZ Axis and YZ Axis.

In this pic you can see curved sides coming off the print bed which is the worst case of this issue. on layer 2 the printer will have a large overhang which always results in a flat side of these objects.

In the case of the rods, they could be printed vertically except for the unnecessary fillets on the sides of them

![Capture](https://user-images.githubusercontent.com/4319326/109476335-195aa580-7a77-11eb-93d1-0d12007a1675.PNG)

In the "rods with clamps" file you did a great job with the print bed overhang, however I still think the alignment of the letters would be even better if you used chamfers on the top as well, but maybe you tested this and it works fine.
![Capture2](https://user-images.githubusercontent.com/4319326/109477423-4a87a580-7a78-11eb-81c9-e94758f813a1.PNG)

**Comment by gavin-owens** [comment]
It works fine without the chamfers, we've definitely tested the alignment. I think it's acceptable to have some overhang on one side of the rods, because only one side needs to rest into the guides. 

So, these changes seem largely cosmetic, which means this can be backlogged — keep it open for more discussion and give Constantine, who is rather busy right now, a chance to consider those changes as well.

What do you think?

**Comment by Schreibmaschine-Berlin** [comment]
The hinges are not cosmetic though, overall the whole print feels very crunchy and I'm having trouble getting things printed and fitting together. especially since these rods go into tunnels that are also printed horizontally. and have overhang on the top, plus the crunchyness of all the layer lines working against each other as it is opening and closing. There are some simple fixes that would allow all the hinges to be printed in the best orientation.

**Comment by gavin-owens** [comment]
I see, but it seems we can close this thread and work out those problems in #2 — if I'm wrong about that please open a new issue or make a comment here to re-open (if this is the proper issue already) with a proposed change like you did for the hinges. The image you used in the other issue was perfectly clear and sets a good precedent for how to propose a change.
